export const categories = [
    {value: 'VENUE_LOCATION', label: 'Venue & Location'},
    {value: 'CATERING_FOOD_SERVICES', label: 'Catering & Food Services'},
    {value: 'DECORATIONS_RENTALS', label: 'Decorations & Rentals'},
    {value: 'ENTERTAINMENT_PERFORMERS', label: 'Entertainment & Performers'},
    {value: 'PHOTOGRAPHY_VIDEOGRAPHY', label: 'Photography & Videography'},
    {value: 'EVENT_PLANNING_COORDINATION', label: 'Event Planning & Coordination'},
    {value: 'INVITATIONS_PRINTING', label: 'Invitations & Printing Services'},
    {value: 'TRANSPORTATION', label: 'Transportation'},
    {value: 'BEAUTY_FASHION', label: 'Beauty & Fashion'},
    {value: 'SOUND_LIGHTING', label: 'Sound, Lighting & AV Equipments'},
    {value: 'RELIGIOUS_CULTURAL', label: 'Religious & Cultural Services'},
    {value: 'GIFTS_FAVORS', label: 'Gifts & Favors'},
]

export const locations = [
    { value: "AMPARA", label: "Ampara"},
    { value: "ANURADHAPURA", label: "Anuradhapura"},
    { value: "BADULLA", label: "Badulla"},
    { value: "BATTICALOA", label: "Batticaloa"},
    { value: "COLOMBO", label: "Colombo"},
    { value: "GALLE", label: "Galle"},
    { value: "GAMPAHA", label: "Gampaha"},
    { value: "HAMBANTOTA", label: "Hambantota"},
    { value: "JAFFNA", label: "Jaffna"},
    { value: "KALUTARA", label: "Kalutara"},
    { value: "KANDY", label: "Kandy"},
    { value: "KEGALLE", label: "Kegalle"},
    { value: "KILINOCHCHI", label: "Kilinochchi"},
    { value: "KURUNEGALA", label: "Kurunegala"},
    { value: "MANNAR", label: "Mannar"},
    { value: "MATALE", label: "Matale"},
    { value: "MATARA", label: "Matara"},
    { value: "MONARAGALA", label: "Monaragala"},
    { value: "MULLAITIVU", label: "Mullaitivu"},
    { value: "NUWARAELIYA", label: "Nuwara Eliya"},
    { value: "POLONNARUWA", label: "Polonnaruwa"},
    { value: "PUTTALAM", label: "Puttalam"},
    { value: "RATNAPURA", label: "Ratnapura"},
    { value: "TRINCOMALEE", label: "Trincomalee"},
    { value: "VAVUNIYA", label: "Vavuniya"},
]